server:
  host: localhost  # Changed from localhost
  port: 8080
postgres:
  host: localhost  # Changed from localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: banking
  sslmode: disable
  uri: postgres://postgres:postgres@localhost:5432/banking?sslmode=disable  # Updated host
kafka:
  brokers:
    - localhost:9092  # Changed to internal Kafka port
  topic: banking-transactions
  batch_size: 100
  batch_timeout: 10
  required_acks: -1
  async: false